### ISSUE TITLE
Wrong file name

### ISSUE THREAD

**Issue by frank89722** [windwords/homebrew-vchewing#1]
`Error: windwords/vchewing/vchewing: Could not find PKG source file 'vChewing-macOS-2.8.7-unsigned.pkg', found 'vChewing-macOS-2.8.7-signed.pkg' instead.`

**Comment by windwords** [comment]
@frank89722 

我忘記改文件名了 新的commit裡面修復了這個問題 
`brew update`一下 再安裝試試
![image](https://user-images.githubusercontent.com/91943226/195108118-0af702a5-740f-4856-a594-4ca57b062c18.png)

**Comment by frank89722** [comment]
沒問題了，謝謝你！
