### ISSUE TITLE
更新後輸入法不會出現在清單 After updating IME won't appear in the list

### ISSUE THREAD

**Issue by hollen9** [windwords/homebrew-vchewing#2]
我執行完 `brew upgrade --cask` 後成功更新 vChewing，
但是還要重新開機才能使用。

請問有辦法執行指令而不用重新開機嗎？感謝

I executed `brew upgrade --cask`, and got vChewing upgraded successfully.
However vChewing did not appear until a full reboot.
Is there any terminal command that can solve this issue?

Thanks for reading.

**Comment by ShikiSuen** [comment]
你可以重新登入。
一般情況下，僅限首次安裝完畢之後才需要重新登入。

**Comment by windwords** [comment]
@hollen9 

這個cask的原理是自動安裝pkg檔，但是對於「[安裝完畢之後重新登入或重新開機](https://vchewing.github.io/README.html#:~:text=%E5%BC%B7%E7%83%88%E5%BB%BA%E8%AD%B0%E5%9C%A8%E5%AE%89%E8%A3%9D%E5%AE%8C%E7%95%A2%E4%B9%8B%E5%BE%8C%E9%87%8D%E6%96%B0%E7%99%BB%E5%85%A5%E6%88%96%E9%87%8D%E6%96%B0%E9%96%8B%E6%A9%9F%EF%BC%88%E5%9D%87%E5%8F%AF%EF%BC%89%E3%80%82)」這種手動操作，沒有辦法實現。 

我建議在安裝/更新完畢後手動重新登入。 

---

The principle of this cask is to automatically install the pkg file, but there is no way to achieve the manual operation of '[re-login or restart after installation](https://vchewing.github.io/README.html#:~:text=%E5%BC%B7%E7%83%88%E5%BB%BA%E8%AD%B0%E5%9C%A8%E5%AE%89%E8%A3%9D%E5%AE%8C%E7%95%A2%E4%B9%8B%E5%BE%8C%E9%87%8D%E6%96%B0%E7%99%BB%E5%85%A5%E6%88%96%E9%87%8D%E6%96%B0%E9%96%8B%E6%A9%9F%EF%BC%88%E5%9D%87%E5%8F%AF%EF%BC%89%E3%80%82)'.

I recommend manually logging back in after the installation/update is complete.

**Comment by hollen9** [comment]
I see. Many thanks for the prompt replies!

**Comment by ShikiSuen** [comment]
@hollen9 不是所有情形都需要在安裝升級完畢之後重新登入/重新開機。
降級的話，必須重新登入/重新開機。
我是覺得這種事情沒必要讓安裝程式來綁架使用者，特別是還有一大堆軟體在運行、不太會想讓人逐個存檔關掉重新開機之後再逐個開啟。

**Comment by ShikiSuen** [comment]
才發現我有回過這串。
不過內容不算重複就是了，權且當作補充說明。
