### ISSUE TITLE
原作者不再於 github 上更新 `vChewing-macOS` 

### ISSUE THREAD

**Issue by CollieIsCute** [windwords/homebrew-vchewing#4]
如標題所述，目前 [vChewing-macOS](https://github.com/vChewing/vChewing-macOS) 已經變成 public archieve repo, 所以之後 vChewing 更新來源可能要換成 gitee

**Comment by ShikiSuen** [comment]
@CollieIsCute 只是有個整天覺得我欠他什麼似的的人來跟我客訴，但我實在沒心思應對了而已。
需要更新的時候我還是會更新，只是倉庫會在更新完畢之後再次 Archive。

P.S.: 我有跟他明碼開價，但我目前真的沒精力也不知道怎樣安排收款手續。

**Comment by windwords** [comment]
@ShikiSuen @CollieIsCute 

我在commit [9a59fc9df3bbdca289e881495369e043a17f7165](https://github.com/windwords/homebrew-vchewing/commit/9a59fc9df3bbdca289e881495369e043a17f7165)中將下載源切換到了Gitee，如果有時間的話麻煩請您嘗試一下是否可用。

\* 由於Gitee的下載伺服器位於中國內地，因此中國內地以外的地區下載速度可能略微降低。

**Comment by CollieIsCute** [comment]
@windwords 您好，其實後來 @ShikiSuen 有解釋之後我就了解了。我後來覺得如果都會更新的話來源是哪個都行，只是我忘記關閉 issue XD 感謝你！

**Comment by CollieIsCute** [comment]
@windwords 我剛剛實際測試重新安裝之後看起來依然是從 github 下載。不過如果 github 下載比較快的話維持 github 也不錯
![image](https://user-images.githubusercontent.com/43088530/232127195-acbda1ad-ea20-4710-8b46-5ca3064ac568.png)

**Comment by windwords** [comment]
@CollieIsCute 您在重新安裝前是否執行了`brew update`？這種情況感覺是Homebrew的快取沒有更新🤔

**Comment by ShikiSuen** [comment]
@CollieIsCute 网路条件允许的话，GitHub 的上传仍旧会尽量更新。
左岸这边（至少我的情况是）上传 GitHub 必须要用虚拟专用网路。
（这也是威注音输入法 dev bleed 分支没有放在 GitHub 的原因。）

**Comment by CollieIsCute** [comment]
@windwords 有了！我在台灣這邊，現在是可以正常從 gitee 下載～
