### ISSUE TITLE
3.6.1 SP1 SHA256 mismatch

### ISSUE THREAD

**Issue by fish-can** [windwords/homebrew-vchewing#5]
如標題所述，
版本 3.6.1 SP1, https://gitee.com/vChewing/vChewing-macOS/releases/download/3.6.1/vChewing-macOS-3.6.1-signed.pkg
的 SHA256 應為 38f5af0cb485d1b224b4c9e0600ca37ae24a93b83019d39b57f2c8bff043f7a3

![image](https://github.com/windwords/homebrew-vchewing/assets/9313825/b98bc25b-d86d-4aca-ba81-34ef3950ac09)

**Comment by ShikiSuen** [comment]
哭枵 我忘记更新 SHA1 了。稍等我修一下。

**Comment by ShikiSuen** [comment]
Fixed. Closing this issue.

Thanks for your report.
