### ISSUE TITLE
3.7.0 SHA256 mismatch

### ISSUE THREAD

**Issue by x9511022a** [windwords/homebrew-vchewing#7]
如標題
現在的sha為6dd2a3dc19e6e1d31afbd1edd5228b22dff5b0f82b5d023e1ff1c52cca79e8d3
<img width="590" alt="截圖 2023-12-29 下午1 57 32" src="https://github.com/windwords/homebrew-vchewing/assets/43727937/f9517f9c-b7d3-4a59-956f-f69b744c7d5c">

**Comment by windwords** [comment]
感謝您回報此問題，對應的SHA256已作修改。

**Comment by x9511022a** [comment]
感謝
成功更新

**Comment by ShikiSuen** [comment]
@x9511022a 
<img width="806" alt="image" src="https://github.com/windwords/homebrew-vchewing/assets/3164826/281bffcf-0fbb-499d-9848-1bf7693145ed">

以 8d3 結尾是給 macOS 10.9 - 12 專用的紀念版。
Homebrew 分支僅託管主流發行版。
這樣一改就全瞎了。

**Comment by ShikiSuen** [comment]
喔原來是我把 homebrew 這邊的填錯了。拍謝。

**Comment by x9511022a** [comment]
看來大大有點累
